// Tasks
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const MOVE_TODOS = 'MOVE_TODOS'
export const UPDATE_TODO_POSITIONS = 'UPDATE_TODO_POSITIONS'
export const FILTER_TASKS = 'FILTER_TASKS'

// Categories
export const CATEGORIZE_TODO = 'CATEGORIZE_TODO'
export const REMOVE_TODO_CATEGORY = 'REMOVE_TODO_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const ADD_AREA_TO_CATEGORY = 'ADD_AREA_TO_CATEGORY'
export const UPDATE_AREA = 'UPDATE_AREA'
export const DELETE_AREA = 'DELETE_AREA'

// TodoForm
export const TOGGLE_TODO_FORM = 'TOGGLE_TODO_FORM'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// Projects
export const ADD_PROJECT = 'ADD_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT'
export const REMOVE_TASK_FROM_PROJECT = 'REMOVE_TASK_FROM_PROJECT'
